### ISSUE TITLE
English menus

### ISSUE THREAD

**Issue by keppi5** [zakki/openhsp#2]
Since source code comments and some dialogs are already in English, menus in hsed.exe need to be translated too. They seem to be in poppad.rc file in hsed3 folder. Here is incomplete version, maybe someone can finish it? 

[Poppad_en.zip](https://github.com/zakki/openhsp/files/1584095/Poppad_en.zip)

**Comment by zakki** [comment]
This repository is unofficial mirror.
I forwarded to official tracker.
http://dev.onionsoft.net/mantis/view.php?id=24

**Comment by keppi5** [comment]
Okay. Unfortunately i don't understand japanese (google translated), apparently the link needs account to view.

**Comment by zakki** [comment]
Merged
